import { StyleSheet } from "react-native";
import { gb } from "../../../screens/globalStyles";
import { isTablet, normalize } from "../../../utils/funcionesMaquetado/responsiveWH";

export const s = StyleSheet.create({
  container: {
    padding: normalize(isTablet ? 24 : 20),
    backgroundColor: "white",
    borderRadius: normalize(10),
    alignItems: "center",
    width: "100%",
    alignSelf: "center",
    ...(isTablet && { maxWidth: 420 }),
  },
  titleModal: {
    fontSize: normalize(isTablet ? 22 : 20),
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: normalize(6),
    color: gb.gray800,
  },
  subTitleModal: {
    fontSize: normalize(isTablet ? 15 : 14),
    color: gb.gray400,
    textAlign: "center",
    marginBottom: normalize(20),
    lineHeight: normalize(22),
    paddingHorizontal: normalize(8),
  },
  input: {
    borderWidth: 1,
    borderColor: gb.gray300,
    borderRadius: normalize(8),
    fontSize: normalize(20),
    textAlignVertical: "center",
    textAlign: "center",
    outlineColor: "transparent",
    height: normalize(isTablet ? 48 : 44),
    backgroundColor: gb.gray50,
    width: "100%",
    maxWidth: isTablet ? normalize(280) : undefined,
  },
  btnConfirmarText: {
    color: "white",
    fontWeight: "bold",
    fontSize: normalize(14),
  },
  iconContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: normalize(16),
    width: normalize(isTablet ? 72 : 64),
    height: normalize(isTablet ? 72 : 64),
    borderRadius: normalize(isTablet ? 36 : 32),
  },
  buttonsContainer: {
    marginTop: normalize(20),
    flexDirection: "row",
    gap: normalize(12),
    justifyContent: "space-between",
    width: "100%",
    maxWidth: isTablet ? normalize(360) : undefined,
  },
  btnCancelarText: {
    color: gb.purple550,
    fontWeight: "bold",
    width: "100%",
    textAlign: "center",
    fontSize: normalize(14),
  },
  btnCancelar: {
    flex: 1,
    backgroundColor: gb.gray50,
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(10),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalize(20),
    borderWidth: 1,
    borderColor: gb.purple550,
  },
  btnConfirmar: {
    flex: 1,
    backgroundColor: gb.purple550,
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(10),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: normalize(20),
  },
});
