import { StyleSheet } from "react-native";
import {
  CONTENT_MAX_WIDTH,
  isTablet,
  normalize,
} from "../../../utils/funcionesMaquetado/responsiveWH";
import { gb } from "../../globalStyles";

export const s = StyleSheet.create({
  header: {
    width: "100%",
    height: normalize(50),
    paddingHorizontal: normalize(10),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cajaContainer: {
    flex: 1,
    alignItems: "center",
    padding: normalize(20),
    backgroundColor: gb.gray50,
    ...(isTablet && { alignSelf: "center", width: CONTENT_MAX_WIDTH }),
  },
  caja: {
    width: "100%",
    borderRadius: normalize(15),
    padding: normalize(20),
    alignItems: "center",
    justifyContent: "center",
  },
  cajaTitle: {
    flexDirection: "row",
    gap: normalize(10),
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  cajaText: {
    color: gb.gray50,
    fontSize: normalize(22),
    fontWeight: "bold",
  },
  containerCristal: {
    height: "fit-content",
    backgroundColor: gb.gray50 + "40",
    padding: normalize(10),
    borderRadius: normalize(10),
    width: "100%",
    marginTop: normalize(20),
    justifyContent: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  metodosCaja: {
    marginTop: normalize(12),
    paddingTop: normalize(10),
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.25)",
    gap: normalize(6),
    width: "100%",
  },
  metodosTitulo: {
    color: "rgba(255,255,255,0.8)",
    fontSize: normalize(11),
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: normalize(2),
  },
  metodoFila: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: normalize(8),
  },
  metodoNombre: {
    color: gb.gray50,
    fontSize: normalize(13),
    fontWeight: "600",
    flex: 1,
  },
  metodoMonto: {
    color: gb.gray50,
    fontSize: normalize(13),
    fontWeight: "700",
  },
  text: {
    color: gb.gray50,
    fontSize: normalize(12),
    fontWeight: "bold",
  },
  containerButtons: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: normalize(8),
    marginTop: normalize(14),
    width: "100%",
  },
  accionBtn: {
    flex: 1,
    minHeight: normalize(62),
    borderRadius: normalize(12),
    alignItems: "center",
    justifyContent: "center",
    gap: normalize(4),
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(8),
  },
  accionDeposito: {
    backgroundColor: "#F3FBF4",
  },
  accionRetiro: {
    backgroundColor: "#FFF5F5",
  },
  accionCerrar: {
    backgroundColor: "white",
  },
  accionAbrir: {
    backgroundColor: "rgba(255,255,255,0.22)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
  },
  accionPressed: {
    opacity: 0.75,
  },
  accionTexto: {
    fontSize: normalize(12),
    fontWeight: "700",
    textAlign: "center",
  },
  contenidoModal: {
    width: "100%",
    padding: normalize(20),
  },
  modalDescripcion: {
    color: gb.gray600,
    fontSize: normalize(12),
    marginBottom: normalize(10),
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  input: {
    flex: 1,
    height: normalize(56),
    color: gb.gray800,
    fontSize: normalize(22),
    lineHeight: normalize(28),
    paddingVertical: 0,
    paddingRight: normalize(14),
    paddingLeft: normalize(42),
    borderWidth: 1,
    borderColor: gb.gray300,
    fontWeight: "bold",
    borderRadius: normalize(8),
    backgroundColor: "white",
    textAlignVertical: "center",
  },
  montosRapidosContainer: {
    flexDirection: "row",
    gap: normalize(10),
    marginTop: normalize(12),
    marginBottom: normalize(8),
    justifyContent: "center",
  },
  conceptoLabel: {
    color: gb.gray400,
    fontWeight: "bold",
    marginTop: normalize(8),
    marginBottom: normalize(6),
    fontSize: normalize(12),
  },
  conceptoInput: {
    minHeight: normalize(84),
    borderWidth: 1,
    borderColor: gb.gray300,
    borderRadius: normalize(8),
    backgroundColor: "white",
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(10),
    fontSize: normalize(13),
    color: gb.gray800,
  },
  montoRapido: {
    backgroundColor: gb.blue200 + "40",
    padding: normalize(10),
    borderRadius: normalize(5),
    borderWidth: 1,
    borderColor: gb.purple550,
  },
  buttonModalCancelContainer: {
    flex: 1,
  },
  buttonModalCancel: {
    backgroundColor: gb.gray100,
    paddingVertical: normalize(10),
    borderRadius: normalize(5),
    alignItems: "center",
    justifyContent: "center",
  },
  buttonModalAcceptContainer: {
    flex: 1,
  },
  buttonModalAccept: {
    backgroundColor: gb.green500,
    paddingVertical: normalize(10),
    borderRadius: normalize(5),
    alignItems: "center",
    justifyContent: "center",
  },
  scroll: {
    flexGrow: 1,
    padding: normalize(20),
    gap: normalize(16),
  },
  historialScroll: {
    flex: 1,
    backgroundColor: gb.gray50,
  },
  cajaWrapper: {
    width: "100%",
    backgroundColor: gb.gray50,
    padding: normalize(20),
  },
  cajaWrapperEnScroll: {
    padding: 0,
    marginBottom: normalize(4),
  },
  historialContainer: {
    width: "100%",
    marginTop: normalize(16),
  },
  historialHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: normalize(8),
    gap: normalize(10),
  },
  historialTitle: {
    fontSize: normalize(14),
    fontWeight: "bold",
    color: gb.gray700,
    flex: 1,
  },
  historialEliminarBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: normalize(4),
    paddingVertical: normalize(6),
    paddingHorizontal: normalize(10),
    borderRadius: normalize(8),
    backgroundColor: "#C5303014",
    borderWidth: 1,
    borderColor: "#C53030",
  },
  historialEliminarTexto: {
    color: "#C53030",
    fontWeight: "bold",
    fontSize: normalize(11),
  },
  historialItem: {
    backgroundColor: "white",
    borderRadius: normalize(14),
    padding: normalize(14),
    marginBottom: normalize(12),
    gap: normalize(12),
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  historialEncabezado: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: normalize(12),
  },
  historialFechas: {
    flexDirection: "row",
    gap: normalize(12),
  },
  historialFechaBloque: {
    flex: 1,
    gap: normalize(2),
    backgroundColor: gb.gray100,
    borderRadius: normalize(10),
    padding: normalize(10),
  },
  historialSeccion: {
    gap: normalize(8),
    paddingTop: normalize(10),
    borderTopWidth: 1,
    borderTopColor: gb.gray200,
  },
  historialSeccionTitulo: {
    fontSize: normalize(11),
    fontWeight: "700",
    color: gb.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  historialLinea: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: normalize(10),
  },
  historialLineaNombre: {
    flex: 1,
    fontSize: normalize(13),
    color: gb.gray700,
    fontWeight: "600",
  },
  historialLineaMonto: {
    fontSize: normalize(13),
    color: gb.gray800,
    fontWeight: "700",
  },
  historialFecha: {
    fontSize: normalize(12),
    color: gb.gray600,
  },
  historialFechaLabel: {
    fontSize: normalize(10),
    fontWeight: "700",
    color: gb.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  historialDevice: {
    fontSize: normalize(12),
    color: gb.gray500,
  },
  historialMonto: {
    fontSize: normalize(18),
    fontWeight: "800",
    color: gb.gray800,
    marginTop: normalize(2),
  },
  historialApertura: {
    fontSize: normalize(12),
    color: gb.gray700,
    fontWeight: "700",
    marginTop: normalize(4),
  },
  movimientoTipo: {
    fontSize: normalize(13),
    fontWeight: "700",
  },
  movimientoFecha: {
    fontSize: normalize(11),
    color: gb.gray500,
  },
  movimientoConcepto: {
    fontSize: normalize(12),
    color: gb.gray600,
    marginTop: normalize(2),
  },
  movimientoMonto: {
    fontSize: normalize(14),
    fontWeight: "700",
  },
  historialEstatusText: {
    fontSize: normalize(13),
    fontWeight: "800",
  },
  historialVacio: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: normalize(10),
  },
  historialVacioTexto: {
    color: gb.gray400,
    fontSize: normalize(14),
  },
});
